### ISSUE TITLE
to see which Tie fighter planet backdrops you are selecting  

### ISSUE THREAD

**Issue by Blazingfirestorm** [MikeG621/YOGEME#105]
when I click backdrop I can't see which backdrop is which so like with XWA having the ability to click on the backdrop

**Comment by MikeG621** [comment]
Does it present the "Platform installation not found" or "Failed to load
backdrop graphics" error?  It reads the backdrops directly from the
installation, that feature's there.

**Comment by Blazingfirestorm** [comment]
![image](https://github.com/user-attachments/assets/bf5ce466-ab29-47c9-b2d4-75c73a3357d2)

**Comment by MikeG621** [comment]
Right, so in the options, on the TIE tab, if it's not able to detect your installation of TIE for one reason or another, it needs to have the installation noted.  You can use the "..." button to select the directory manually.  That message means it thinks TIE is installed, but it didn't find the files where it's expected.  Specifically for TIE, it's looking for "\IVFILES\PLANET#.ACT", 1-8.
YOGEME doesn't come with any of the backdrop images, even for XWA.
![image](https://github.com/user-attachments/assets/8a836473-3ac9-4168-9759-4748ccae260c)

**Comment by Blazingfirestorm** [comment]
yep I fixed it in the directory I had the 95 version  thanks for the help
