### ISSUE TITLE
TIE Briefing Question overflow

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#106]
If you have loaded more than one TIE mission since you have launched the editor, when you go to the briefing officer/secret order questions you will see not only the text for the mission you are currently editing/viewing but also the text for every other mission you have loaded that session.

**Comment by JaggedFellIII** [comment]
![Screenshot 2024-09-17 194126](https://github.com/user-attachments/assets/10a09d8a-94ac-4790-88b0-a44ca0d731b1)
![Screenshot 2024-09-17 194054](https://github.com/user-attachments/assets/1e9a3735-f877-4a6d-a78d-d944243e29f5)
![Screenshot 2024-09-17 194020](https://github.com/user-attachments/assets/e1fee489-63e2-4631-9b35-e43f44c92a1f)

**Comment by MikeG621** [comment]
Already fixed for the next release, ecfbaea.
