### ISSUE TITLE
Latest YOGEME listed as false positive

### ISSUE THREAD

**Issue by NLG24** [MikeG621/YOGEME#108]
Hello, this is NLG24 and I have a technical problem,

![image](https://github.com/user-attachments/assets/fa14a15c-676d-44be-81c0-e94d669a33ed)

The latest version of YOGEME did not open because my laptop recognizes it as a false positive. The pop-up window reads:

"Operation did not complete successfully because the file contains a virus or potentially unwanted software."

**Comment by MikeG621** [comment]
What AV software are you using?  I've run it through VirusTotal and the only thing that complained is MaxSecure, which apparently is known to flag everything under the sun as being a Trojan and can be ignored.

**Comment by NLG24** [comment]
I just ran the scan with Windows Defender and it picked up what is supposedly a Trojan.

![image](https://github.com/user-attachments/assets/a1f4770e-1efe-49d1-8b6c-fe1a88031c24)

**Comment by MikeG621** [comment]
[VirusTotal results](https://www.virustotal.com/gui/file/9e920c5f9470011b998047f7a96ce2039318b22cbecdfac47ca790f36b040453), Microsoft (and everyone else) shows it clean there.  The ML extension means your local Defender install is guessing based on what it thinks it can do, not if it's actually dangerous.  The machine learning tools aren't the greatest, and can decide a text file or image you've had for years has suddenly gained the ability to connect over the internet.

I can try to submit for whitelisting, but that can take a while and then you'd have to update your install.  Just "allow on device", maybe your ML will learn it's safe.

**Comment by NLG24** [comment]
Done. I'll start up YOGEME right now.

**Comment by NLG24** [comment]
It works! Despite little hesitation, thank you for the technical support.
