### ISSUE TITLE
Hook Editor

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#109]
No longer does the hook editor crash, but none of the changes save when i hit ok and save the mission

**Comment by JaggedFellIII** [comment]
Actually, won't let me save a mission file at all

**Comment by MikeG621** [comment]
Confirmed that the hook INIs aren't saving like they should, but mission save is working fine.

**Comment by MikeG621** [comment]
It'll create new INIs just fine, but for existing files it's restoring the backup which is the fallback behavior if there's a problem.

**Comment by JaggedFellIII** [comment]
still having the issue of the 1.6 version not saving at all on my computer

**Comment by MikeG621** [comment]
It's saving normally on my end.  Can you save in folders other than the XWA installation? Like just on your desktop?

**Comment by JaggedFellIII** [comment]
I can save by using Save As but the simple Save button is not working, no
matter the folder

**Comment by MikeG621** [comment]
When you're trying to save, does the title bar text end with the "*" character?  That's the only thing i can see right now that would prevent saving the mission without an error message; it doesn't run through the save if it's not modified.
