### ISSUE TITLE
Resizing Windows

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#11]
Having the ability to freely rescale windows would allow for a modifiable workspace.

**Comment by MikeG621** [comment]
Certain tabs/windows may work well for expanding (FG list vertically, for
example) but other panels don't contain anything that would benefit from
resizing.  I can certainly go through and see what's feasible but in a lot
of cases making the window larger will just create a tone of dead space.
Is there any window into particular you want to rescale?

--
Michael Gaisser
850-396-4535

**Comment by ual002** [comment]
Mainly the map interface.

**Comment by MikeG621** [comment]
Okay, the map interface I can convert to resizable easy enough, I'll take a
look this weekend.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
Latest [commit](https://github.com/MikeG621/YOGEME/commit/d5498ac01ed4652108b5edc640bfab3d39e8f29d) makes the map interface resizable

**Comment by MikeG621** [comment]
LstForm also updated, committed.  Don't really see anything else that would benefit from it.

**Comment by MikeG621** [comment]
v1.4 released.
