### ISSUE TITLE
Briefing tab not working right

### ISSUE THREAD

**Issue by NLG24** [MikeG621/YOGEME#112]
Hello again, I found another set of problems regarding creating and editing briefings on YOGEME.

The Briefings tab in the Briefing Editor for XWA has most functions leading to multiple unique "Unhandled Exception" errors. Text Tag, FG Tag, NewPage, Region #, and Caption have these errors so far.

To sum this up, the Briefings tab is mostly broken in the Briefing Editor.

**Comment by MikeG621** [comment]
What version are you running?  Working fine for me.

**Comment by NLG24** [comment]
The latest version 1.16.0.4 including bug fixes.

**Comment by MikeG621** [comment]
Alright, then walk through exactly what you're doing.  Is this with a new mission and empty briefing? Existing one?  Event time of an existing event, or inserting somewhere?

**Comment by NLG24** [comment]
Yes, new mission, empty briefing, as if I am creating an entirely new mission.

**Comment by MikeG621** [comment]
Found it, sorted now.
