### ISSUE TITLE
Mission Verify - backdrop FGs with no orders are incorrectly flagged

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/YOGEME#15]
Because why would a backdrop object ever need orders?

**Comment by MikeG621** [comment]
Those shouldn't be flagged.  Which platform did you run MV on?

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
Windows 7 64-bit, AMD Phenom II quad core.

**Comment by MikeG621** [comment]
I meant for which game, but given your other report I'm guessing TIE.  MV
is an external application, but I can go back and remove the Backdrops from
the orders check.

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
No, it's XWA. Recall TIE isn't even being recognized for me at the moment.

**Comment by MikeG621** [comment]
Dug out MissionVerify source code and uploaded, starting to modernize it since it's over 10 years old.

**Comment by keiranhalcyon31** [comment]
Cool.  I've noticed a few other issues with it.  I'll open tickets on its own repository for them, though.

**Comment by MikeG621** [comment]
Fixed in [MissionVerify v2.0](https://github.com/MikeG621/MissionVerify/releases/tag/v2.0), YOGEME [re-released](https://github.com/MikeG621/YOGEME/releases/tag/1.4.1r2) with the update.
