### ISSUE TITLE
Waypoint y-coord inversion issue

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/YOGEME#16]
On the waypoint tab, the y-coordinate is inverted for the startpoints and hyperspace point (so that positions above the origin are positive values, opposite of native), but the inversion is missing for the orders waypoints.  This affects both the numerical fields and the map display.

**Comment by MikeG621** [comment]
I need to know the platform.

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
Windows 7 64-bit, AMD Phenom II quad core.

**Comment by MikeG621** [comment]
Again, by "platform" I mean which game, but I'm guessing TIE.

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
Oh. XWA, actually.

**Comment by MikeG621** [comment]
Fixed over in [Platform](https://github.com/MikeG621/Platform/commit/7bcbe7200d996791f64b893aa48990a5b8875312), the inversion was missing

**Comment by keiranhalcyon31** [comment]
Thanks!
