### ISSUE TITLE
TIE Fighter Steam install not detected

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/YOGEME#17]
At startup, TIE Fighter is grayed out.

**Comment by MikeG621** [comment]
Which version of TIE Fighter do you have installed?  It should detect TIE95.

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
All three of "classic", "collectors_cd", and "remastered" (TIE95) are installed from Steam.  Full path to TIE95.EXE is G:\SteamLibrary\steamapps\common\STAR WARS Tie Fighter\remastered\TIE95.EXE

Platform: Windows 7 64-bit, AMD Phenom II quad core.

**Comment by MikeG621** [comment]
I'll double check the detection for Steam.  Do you have more than one
Library location, or are all of your Steam applications installed in the
same place?
Even though TIE isn't recognized automatically, you can still turn it on
through the options and manually set the installation directories.
-On the "Overall" tab, uncheck "Only allow editing for installed platforms".
-On the "TIE" tab, check the "Installed" box and you can paste the
directory in the text box or use the "..." button to select the
"\remastered" folder via dialog.

--
Michael Gaisser
850-396-4535

**Comment by keiranhalcyon31** [comment]
Ok, thanks, I'll take a look at those options.

I do have a second (well, first) Steam library on c:, but like I said, it wasn't a problem for XvT or XWA.

**Comment by MikeG621** [comment]
Steam isn't creating the legacy registry key that was used in the original
releases (may be a part of the compatibility fix), which is why the
detection is failing.  I've got an idea on how to get around that, though.

--
Michael Gaisser
850-396-4535
