### ISSUE TITLE
Escort order additional functionality

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#18]
The top "meaningless" variable on the Escort order is actually an anchor point.  If you want to add in this functionality I can continue my research and verify all the iffy ones.  See my thread here.  

http://www.xwaupgrade.com/phpBB3/viewtopic.php?f=9&t=10819#p144972

Here's the basics as they apply to ALLiED

The bottom left "No Effect?" setting for the escort (prevent boarding) order should be called "Position in relation to escortee", or "anchor point". Setting the escort's formation like normal will give it that formation with the following desired "anchor point" or "no effect?" setting in relation to the escortee. With some testing I was able to replicate this formation [https://i.imgur.com/NANrx2c.png] with the following settings.

44 - Far trail 
27 - lead escort centered on escortee (causes collisions)
26 - right low rear 
25 - Low rear ***
24 - Left low rear 
23 - Right low 
22 - Low centered on the number 1 escort
21 - Left low
20 - Like 11 but low
19 - Low "vic", escortee in center **** (this translates to front low)
18 - Like 9 but low.
17 - Right rear ****
16 - rear *****
15 - Left rear *****
14 - Unknown Formation (Vic Right?)
13 - Single point? (Causes player collisions)
12 - Left rear ?
11 - Vic, but the escortee is wedged between the number 3 and number 5 slot, if you consider the lead escort as 1. (This translates to lead escort anchored front right)
10 - Vic, escortee may be directly behind 1 slot. (Results in player collision)
9 - Vic, but the escortee is wedged between the number 2 and number 4 slot, if you consider the lead escort as 1. (This translates to lead escort anchored front left)
8 - Right high rear 
7 - High rear 
6 - Left high rear 
5 - Right high 
4 - High vic, escortee in center ***** (this translates to front high)
3 - Left high 
2 - Like 11 but high
1 - Similar to 4
0 - Like 9 but High

**Comment by MikeG621** [comment]
Yep, had seen the thread and mentally added it to the to-do list.  Adding
it to the tracker will keep me honest, thanks.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
I've added the "Position" label to the parameter for the order to [Platform](MikeG621/Platform) for the time being.  Haven't decided how I want to implement it fully yet

**Comment by ual002** [comment]
Having another person verify my numbered position findings and maybe figure out a standard nomenclature could be helpful.  You could then just assign those values to the numbers.

**Comment by ual002** [comment]
I started this based of some raw data someone extracted

https://docs.google.com/spreadsheets/d/1SZbYU69NsuoJMUfimDYJwRf_aI7eyoVpZe274Z5CHOM/edit#gid=0

**Comment by MikeG621** [comment]
Excellent. I think the "friendliest" way will be to use the nomenclature
instead of numbered values (means having to fiddle with the ComboBox's
size), and I think I'll wind up using "Leading/Trailing" instead of
"Front/Rear".

So with 27 being the same as 13, does that lead to everything afterwards
(28, 29...) also being the same?  If so we'll just cut it off at 26.

--
Michael Gaisser
850-396-4535

**Comment by JeremyAnsel** [comment]
No. 27 is (0, 0, 0) (same as 13) and can be ignored. Setting a value > 27 leads to undefined behavior. The game doesn't check that the value is between valid range. So valid numbers are from 0 to 26.

**Comment by MikeG621** [comment]
Added a new label next to the number to denote what it means, instead of
changing the control from a Number to Combo.

--
Michael Gaisser
850-396-4535

**Comment by ual002** [comment]
All sounds good. Leading/Trailing is better I agree.
