### ISSUE TITLE
Flight group colors beyond 4

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/YOGEME#21]
It's recently been discovered that the XWA game engine supports more flight group colors that four (http://www.xwaupgrade.com/phpBB3/viewtopic.php?p=154222#p154222).  Currently the only way to access this functionality is to use a hook by JeremyaFr, or edit the binary of the mission file directly.  This request is to expose this functionality in Yogeme by replacing the 4-option dropdown with a text field for values 0-255 (or whatever the range is for that field in the .tie format).

This would dovetail well with the future opt loading support, as the combination would allow you to preview the settings you've selected.

**Comment by MikeG621** [comment]
I'll probably keep it a drop-down so the stock text remains, just add the
rest of the range as numbers. I've got a large update I'm reviewing right
now and I'll roll it into that.

**Comment by MikeG621** [comment]
Added, will be part of next release
