### ISSUE TITLE
MACHINELEARNING/ANOMALOUS.100%

### ISSUE THREAD

**Issue by CyrelV** [MikeG621/YOGEME#22]
In the most recent release, MALWAREBYTES reports 'MACHINELEARNING/ANOMALOUS.100%' is present in YOGEME.exe. 

From their forums, it seems as though this may be due to whatever packaging method you used to bundle the exe. They list ENIGMA as a culprit (see: https://forums.malwarebytes.com/topic/215911-malwarebyte-false-detected-my-software-as-machinelearninganomalous100/ ).

**Comment by MikeG621** [comment]
And after reading that thread, looks like MB just dorked something up on
their end and is flagging all sorts of things for no reason.

--
Michael Gaisser
850-396-4535

**Comment by JeremyAnsel** [comment]
VirusTotal marks the file as clean:
https://www.virustotal.com/#/url/b032e608e284ca29437d36c185c87c3587055379865c358ffb8856d35c85bae3/detection
https://www.virustotal.com/#/file/68bf3c90561d60c80c787af0d22ec08ce3841fb8c755088afb60799c882b681d/detection

**Comment by CyrelV** [comment]
Yeah, I figured as much. 

Just wanted you guys to be aware / let others know if it comes up for them.
