### ISSUE TITLE
Multiple Selection

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#23]
I think this would be a great feature to have and save a lot of time in creating missions.

**Comment by MikeG621** [comment]
Multiple what? Flightgroups? Triggers? Orders?  Multi-select was just added
to the map to drag waypoints around.

**Comment by bguthrie1** [comment]
Multiple Flight Group selection. Such as changing multiple FGs IFF at once.

**Comment by ual002** [comment]
+1 for that.

**Comment by MikeG621** [comment]
Left as open until the rest of the platforms are done

**Comment by ual002** [comment]
Curious if the multiple selection of flight groups to change info in multiple FG at the same time is functioning (and I dont know how to do it, or if its still WIP)

**Comment by MikeG621** [comment]
Yes, that works.  Ctrl+click FGs in the list, the one shown in the tabs
will be the highest listed FG.  Then whatever you change will be reflected
in all of them.  Simply click a single FG to cancel the multi-select.
Multi-select also works for Messages.
--
Michael Gaisser
