### ISSUE TITLE
YOGEME error upon start

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#24]
I get this error when opening a BOP mission: 
<img width="307" alt="yogemeerror" src="https://user-images.githubusercontent.com/43460482/46048948-c2e82080-c0e0-11e8-95ff-cdd210fd96c1.PNG">

I can reproduce this by opening an Xwing mission first, then attempting to open a BOP mission.

Deleting the Settings.dat file fixes it for a time until I do the above again.

**Comment by MikeG621** [comment]
Which mission in particular?
--
Michael Gaisser

**Comment by bguthrie1** [comment]
Any mission (both X-Wing or BOP) triggers the message.

**Comment by bguthrie1** [comment]
Here is settings file by the way
[Settings.zip](https://github.com/MikeG621/YOGEME/files/2417480/Settings.zip)

**Comment by MikeG621** [comment]
Can you also please attach just the ATTACKXY.XWI you were trying to open?
I want to make sure that it's 100% the same for your GOG install as it is
for my Steam install.  I'm opening everything fine on my end, so I need to
verify where the 92 is coming from.

Also, I see that you're set to "Open Last Mission" on startup.  Does this
happen just during startup, or anytime you try to open a mission once it's
already running?
--
Michael Gaisser

**Comment by bguthrie1** [comment]
Here is ATTACKXY. I've edited the mission in that the player craft is different but the mission remains the same as the original. 
[ATTACKXY.zip](https://github.com/MikeG621/YOGEME/files/2417639/ATTACKXY.zip)

I've set the mission file formats to open using YOGEME so I just double click on the mission and I get the error.
