### ISSUE TITLE
Missions are considered "modified" if the briefing dialog is opened

### ISSUE THREAD

**Issue by chrisforbes** [MikeG621/YOGEME#30]
If no changes are made in the briefing dialog (eg the briefing was simply played) it would be nice if the mission was not considered dirty. Currently browsing through missions and checking their briefings produces spurious "would you like to save" dialogs.

**Comment by MikeG621** [comment]
I'm implementing Callbacks, similar to MapForm and that'll take care of
this.  It'll take a little bit to get there.
--
Michael Gaisser
