### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by RedDragonWebDesign** [MikeG621/YOGEME#37]
Steps to reproduce

- Windows 7
- Download v1.7
- Don't change any configs or default settings
- Double click YOGEME.exe
- Check "Tie Fighter"
- Hit OK
- Doesn't crash, but pops up the below warning

![image](https://user-images.githubusercontent.com/43397938/92426286-656b0400-f13e-11ea-99b3-46bff0b886b3.png)

**Comment by MikeG621** [comment]
Check the options dialog and see if it has a path for TIE.  First guess is
that it didn't detect the installation, which would cause the ship list to
fail.
--
Michael Gaisser

**Comment by RedDragonWebDesign** [comment]
Path appears to be correct. Confirmed that I'm still getting the error.

![2020-09-07_194010](https://user-images.githubusercontent.com/43397938/92427724-11fab500-f142-11ea-9057-4d2bc4a6c1b7.png)

**Comment by MikeG621** [comment]
No, on the TIE tab.  You're looking for it to look something like this:
[image: image.png]

--
Michael Gaisser

**Comment by RedDragonWebDesign** [comment]
Yeap, you're right, it appears to be blank.

If interested in fixing, maybe have it populate with the path of the running executable, or maybe silence the warning popup?

![image](https://user-images.githubusercontent.com/43397938/92428069-08be1800-f143-11ea-849c-9978eaa205e2.png)

**Comment by MikeG621** [comment]
No, it cannot be auto-populated by a default value because that's the path
for the actual game, not YOGEME or anything that comes with it.  There's
going to be several other features that will not function if TIE is not
installed (likewise for the other platforms).  However I will look into
making this particular error mode silent, without breaking the other error
checks.
--
Michael Gaisser

**Comment by MikeG621** [comment]
Found the bug, so the error itself is fixed now.  Nothing will change
functionally, there will still be features unavailable without TIE
installed, but the error itself won't occur in the next update.
--
Michael Gaisser
