### ISSUE TITLE
xvt conversion to xwing alliance

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#43]
HI Michael,

I have tried to convert one original mission file from from xvt to xwa.

But unfortunatenly don't load this file (the game exit while trying to load the file) 

Attached the output file.
[output (xwing alliance).zip](https://github.com/MikeG621/YOGEME/files/5934797/output.xwing.alliance.zip)

Do you known if your converter is compatible with the last xwa update ?

Thanks !

Marco

**Comment by MikeG621** [comment]
The XWAUP patch doesn't affect how missions are loaded, so the format
itself hasn't changed.  Which mission was the original so I can compare?
--
Michael Gaisser

**Comment by MikeG621** [comment]
You have to name the mission file properly in XWA, it can't just be
whatever you want.  Once I added a "1B0M1" prefix to the mission name (so
"1B0M1output.tie") it loaded just fine.
--
Michael Gaisser
