### ISSUE TITLE
Error when hitting backdrop button

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#44]
![image](https://user-images.githubusercontent.com/7959255/107729722-3f322d00-6cb7-11eb-8609-1826bde03983.png)
Unsure what the cause is but I am testing TFTC beta and this could be something about the ordering of stuff in the resdata.txt?  Unsure

**Comment by MikeG621** [comment]
Custom DATs must be at the top of the file, but that it tried means it
found it so that's not the issue.
Is that path as shown correct?  Namely the filename itself, and that it's
not supposed to be XWAU2.dat in a ShipStuff directory.
--

**Comment by MikeG621** [comment]
This was fixed in [v2.3](https://github.com/MikeG621/ImageFormat-Dat/releases/tag/v2.3) of the Dat.dll (related to empty groups).  Issue finally emerged on my end with XWAUP v3.  YOGEME [v1.10.2 ](https://github.com/MikeG621/YOGEME/releases/tag/v1.10.2) includes the new dll.
