### ISSUE TITLE
[question] A bit confusion about sharp char in mission failed / description / successful

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#47]
Hi,

I like to give a confirm about the sharp char (#) for xwing alliance missions.

For what I see seem to work fine:

1) In the mission description must put at the end of description.
2) In the mission failed the first char must be "sharp" otherwise you don't see the description.
3) Not clear about mission successful. Must be put at the end of message like in  mission description ?

I forget to ask another question:

How I can see if a mission is linked to a cutscene ? There is a way to test it in the simulator ?

Thanks !

**Comment by MikeG621** [comment]
For the description, the first part before the "#" is the simple
description that you see in the mission select or pre-briefing.  After the
"#" is the words that you hear in the voiceover before the briefing starts
during normal play (not Simulator).  So custom missions generally don't
need anything after it unless you're going through the trouble of recording
audio.  If you forget to use it at all, YOGEME will add it at the end.

Failed, yes it must start with it.  It looks like they meant for it to have
a general summary displayed at one point in addition to recorded audio, but
they never did.  So in a sense it operates the same as Description, it's
just that visibly you're using the other half of it.  If you forget to use
it at all, YOGEME will add it at the beginning.

Successful, there's no #, the summary and audio text are the same.
--
