### ISSUE TITLE
XWA, CopyFlightGroup: Idmr.Platform.BaseTrigger is not marked as Serializable

### ISSUE THREAD

**Issue by JeremyAnsel** [MikeG621/YOGEME#5]
When copying a flight group, a `SerializationException` exception is thrown. It says that  `Idmr.Platform.BaseTrigger` is not marked as `Serializable`.

How to reproduce the issue:
- open YOGEME.exe v1.2.5
- select XWA platform
- click on CopyFlightGroup

**Comment by MikeG621** [comment]
Hmm, another error that I know didn't exist in the past.  Fixed in the next upload
