### ISSUE TITLE
[Imformation] Edit all mission goal string messages

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#50]
Hi Mike,

Please excuse me I need a information:

In this file there is a mission goal string: "Frigate Meteor: not destroyed"

[1b22m1xvt.zip](https://github.com/MikeG621/YOGEME/files/6136778/1b22m1xvt.zip)

I have translated this file at 95-99% but I have not understand where I can edit this string to translate it.

If I open this file with notepad see this text, but francally I don't like use notepad to operations like this.

Can you please tell me how I can edit this string ?

Best Regards

**Comment by MikeG621** [comment]
Goals tab, Goal 3, "100% of Flight Group must exist"
--
