### ISSUE TITLE
xwing conversion order seem different

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#55]
Hi Mike,

Today I have complete other tests and my impression is that there is some difference between original files:

![order4](https://user-images.githubusercontent.com/55355625/112810311-2d47f600-907b-11eb-8d48-83a6efc8b61b.png)

Here there is a % difference (50% and 75%).

In this case my impression is allied conversion seem wrong I ask your confirmation:

![orders2](https://user-images.githubusercontent.com/55355625/112810528-6718fc80-907b-11eb-88f7-7a5d117e7dd1.png)

Here all details:

[difference.zip](https://github.com/MikeG621/YOGEME/files/6220399/difference.zip)

Thank you !

Marco

**Comment by MikeG621** [comment]
There are certain things that cannot be converted perfectly, since the
games are completely different.  The order that YOGEME uses was found
during testing to behave more like it did in XW, that is working as
intended.

The amounts however should've come over properly, that I'll need to look
into.
--

**Comment by luca2125** [comment]
Thank you, Mike, you confirm my impression.

About Allied conversion, seem wrong becouse "Await border" is different from "Disable", do you agree ? Or you think can be acceptable ?

In this case YOGEME seem more closed to original.

**Comment by MikeG621** [comment]
Yes, the biggest problem with "Disable" is just that; the ship is disabled
and doesn't do anything.  The original Await allowed the ship to shoot
back.  There's other similar order conversions that are picked out like
that to get around behavior differences.
--

**Comment by luca2125** [comment]
Hi Mike,

In the meantime iI like a suggest from your side.

I like to optimize the xwing cutscene I have recorded one sample:

https://user-images.githubusercontent.com/55355625/113173099-5c13c700-9249-11eb-9916-10501de06f2e.mp4

This came from xwing special edition 1998, that use 3d hardware support but the result is too much pixels effect.

Do you known if there is a way the play better the cutscene ? (example play the cutscene to a modern engine xwa or other alternative ..)

Thank you in advance.

Marco

**Comment by MikeG621** [comment]
No, they are effectively animated Bitmaps.  The 3D support is for the
flight engine, not cutscenes.
--

**Comment by MikeG621** [comment]
Amount conversions are fixed in [v5.4 of Platform](https://github.com/MikeG621/Platform/releases/tag/v5.4), download and drop it in the /bin directory.

**Comment by luca2125** [comment]
Many thanks Mike !!

I will download the last version and continue with the conversion.

I will let you known..

Happy Estern
