### ISSUE TITLE
Briefing summary duplicate

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#57]
Hi Mike,

Just tested the last updated version and I have found a strange thing:

[strange_briefing_summary.zip](https://github.com/MikeG621/YOGEME/files/6259325/strange_briefing_summary.zip)

In the briefing summary the last line is a duplicate of the first line.

I don't known why. 

Can you check please ?

Apart this another secondary situation that is not very important, but can be useful if is possible fix it: In all conversions the first briefing string of array is always "Empty" and start from the 2nd. The "Allied Conversion" start from first. This cause difference from audio wav file names between the 2 conversions (I need to rename all audio files). However I repeat this is secondary and not important.

Best Regards

Marco

**Comment by MikeG621** [comment]
If you looked at the original X-wing mission you'd see the caption command
twice, and the first string is empty.  The conversions are doing exactly
what they're supposed to, the original is like that.  No issue, closing.
--
