### ISSUE TITLE
XWA, Exit confirm dialog is shown twice

### ISSUE THREAD

**Issue by JeremyAnsel** [MikeG621/YOGEME#6]
When you close the window, the confirm dialog is shown twice.

How to reproduce the issue:
- open YOGEME.exe v1.2.5
- select XWA Platform
- close the window
- click `Yes`

**Comment by MikeG621** [comment]
While closing the form, after confirm exit it calls Application.Exit() which in turn executes the form close again.  Fixed for the next upload, XvT and TIE also repaired.

**Comment by MikeG621** [comment]
Issue appears to apply to XWA only, even though shut down code is same among all three platforms
