### ISSUE TITLE
CHM file doesn't render?

### ISSUE THREAD

**Issue by smfritzii** [MikeG621/YOGEME#66]
Hi there,

I downloaded the 1.12 release and opened the CHM file, but none of the pages are rendering.  Windows 10.0.19042 if that's important. Screenshot attached.

Thanks

![help](https://user-images.githubusercontent.com/4137730/149832447-9619777a-9f3c-4d5d-8ef2-362f31262d07.png)

**Comment by MikeG621** [comment]
Right-click the CHM and go to Properties, see if the "Unblock" box is
ticked and uncheck it if it is.
--
Michael Gaisser

**Comment by smfritzii** [comment]
The "unblock" option was unticked. I checked it and it seems to be rendering. Thanks.
