### ISSUE TITLE
Extent the chars limit on in-flight message

### ISSUE THREAD

**Issue by luca2125** [MikeG621/YOGEME#69]
Hi Mike,

On discord (Tie Fighter Total Conversion -> Feedback and suggestion)

https://discord.com/channels/851918539496620062/851926711796760576

we are talking about the possibility to extend the limit of flight message chars that actually is only 70 chars.

Can you please join the discussion if you can ?

**Comment by MikeG621** [comment]
Extended to 68 char in e455fd6, and [Platform:5ff546a](https://github.com/MikeG621/Platform/commit/5ff546a8dd4fb9e47449db7e909a628403fc079e)

**Comment by luca2125** [comment]
Thank you Mike, before this modification what was the previous limit of chars ?

**Comment by MikeG621** [comment]
Previous limit was 64, that's what it's been since TIE.  Going to leave
this open for now in case the discussion of hooks go further, but the file
format is the current source of the limit.
