### ISSUE TITLE
Mission Verification asks to drag a file when launched from YOGEME

### ISSUE THREAD

**Issue by JeremyAnsel** [MikeG621/YOGEME#7]
When a mission file path contains a space, `MissionVerify` asks to drag a file instead of checking the mission.

How to reproduce the issue:
- open YOGEME.exe v1.2.5
- select XWA platform
- save the mission with a file path containing a space

**Comment by MikeG621** [comment]
This is going to be a problem with MissionVerify, not YOGEME.  That's 8-9 years old and isn't in my active projects directory, I'll have to restore it and up-convert it.  You can disable that MV check in the Options dialog to get around it.  The issue will stay open until I get that project loaded.

**Comment by JeremyAnsel** [comment]
Maybe there is something wrong with the command line arguments when launching MissionVerify.
Are the file name surrounded with double quotes (").

**Comment by MikeG621** [comment]
Should just be passing string objects.  In either case, MV should be able
to handle a space or be made able to when launched from command line.  When
I get the project unpacked I'll be able to check it from that end and see
what it's receiving.

--
Michael Gaisser
850-396-4535
