### ISSUE TITLE
LST Editor

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#70]
![image](https://user-images.githubusercontent.com/7959255/187077929-585b91f6-b589-4105-ac51-d469bb7b5a42.png)

Can support be included for the COMBAT folder missions from Justagai's MP Hook? IE COMBAT\MISSION.LST?

**Comment by MikeG621** [comment]
Sure, that'll be an easy add.
--
Michael

**Comment by MikeG621** [comment]
Added in 1.13.8
