### ISSUE TITLE
Clicking the backdrop button Causes multiple errors

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#71]
When clicking the backdrop button to edit backdrops, several dat reading errors pop up (this is for TFTC).  I am unsure what the issue is, but it seems like after clicking thru all the errors, I finally get the dat picker to come up.  While the errors may need further investigation, the work flow is constantly interrupted.

![image](https://user-images.githubusercontent.com/7959255/187087114-2f3ae0d2-061c-4131-be26-e330417e1151.png)

**Comment by MikeG621** [comment]
Known issue, that is a problem with TFTC; they include way too many DAT
files in RESDATA including those that don't exist.  I'd rather not remove
that warning as that can point to actual problems, it's easier to remove
the offending lines from the mod's RESDATA.
--
Michael

**Comment by ual002** [comment]
Ok, I've raised the issue in the TFTC Discord.  Maybe some master file is pointing to outdated Dats.

**Comment by ual002** [comment]
There is also a new type of compression Jeremy provided, 25c, I'm wondering if thats part of the issue, maybe if your dat reader isnt reading those.  I need to dig deeper.

**Comment by ual002** [comment]
While we investigate, is there a way to maybe have the ability to turn off repeat error messages in the options, especially if its actually functionality still works after powering thru the errors?

**Comment by MikeG621** [comment]
The last upload should take care of it, but I'm remote and won't be able to
test for a few days

**Comment by MikeG621** [comment]
25c's already implemented, did that back in March.  That's why I know TFTC
is pointing to DATs that don't exist, had Angel send me some files a while
back so I could test it prior to release.  Pretty sure I had mentioned it
to him, but as it was still WIP I couldn't know for sure if those were just
files I didn't get.
