### ISSUE TITLE
(TIE Fighter) After ejection pilot is...

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#73]
This feature does not work. I've checked the assembly and it actually does nothing. The feature that controls whether a player is captured or rescued depends on whether the secret order monk is there in any capacity. The way it works is this:

- Player must be flying a mission in a Battle.
- Check if Secret order monk is one of the briefing officers in the mission. If so, the player is always rescued.
- If not, and the player's craft is destroyed (ejected not killed), check for the nearest enemy (Rebel or IFF Red, doesn't matter if Red is set as friendly in the mission) and friendly (IFF Imperial) that are transport class or higher that have arrived in the mission.
- Get the distance of the two to the player. Divide the friendly distance by 2. If the friendly is nearest to the player, the player is rescued. Otherwise, the player is captured.

By the way, this above also applies to X-wing (except Rebels and Neutrals are friendly and Imperials are enemies). Only the briefing officer is the end event and only if its set to 0, 2 or 4. Its a bitfield just like the briefing officer value in TIE Fighter and in X-wing's case you only have to care about 0, 1 and 5. Values 1 and 5 also mean that the player is always rescued. Also Neutral IFFs are not considered enemies for this feature, even if they are hostile.

Screenshot of the setting in YOGEME. My recommendation is to have it removed entirely.
![yogeme1](https://user-images.githubusercontent.com/43460482/190874015-ab3a6fe3-3ef6-4fca-869c-3c976ac24f19.png)

**Comment by MikeG621** [comment]
I vaguely remember something once upon a time about the outcome being influenced by proximity to other ships, though the Secret Order being present causing automatic rescue is interesting.

**Comment by bguthrie1** [comment]
I've made a little addendum in regards to the capture feature in X-wing that IFF Neutral are considered friendlies there. The same is not considered in TIE Fighter. They just aren't counted at all. Though if there are no friendlies and just neutrals or nothing at all, player is rescued anyway.

In regards to the Secret Order rescuing the player everytime, I like to think they always have a plan of rescuing or bailing the player out of prison if they are captured. They care about the player as they are a very special asset to them.
