### ISSUE TITLE
(TIE Fighter) Secret Goal

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#74]
The secret goals feature in YOGEME is not used in TIE Fighter. Originally it was supposed to be a prevent condition like in XVT and XWA but was never finished. 

Recommendation is to remove the Secret goals from YOGEME since they are not used. 
Screenshot attached of the feature.
![yogeme2](https://user-images.githubusercontent.com/43460482/190876988-b3bd8737-c3d4-407a-9616-3a6883178d84.png)

**Comment by MikeG621** [comment]
Is it completely ignored by the executable?

**Comment by bguthrie1** [comment]
I've checked all functions that reference the goal type. Its the 3rd goal type, index 2, 0xA2 in the mission FG table. There is no mention of this type in any part of the code interestingly enough. So yeah completely ignored by the executable.
