### ISSUE TITLE
(TIE Fighter) Trigger Condition 0x18

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#75]
Its listed as unknown (arrive?) in YOGEME. It is Cannon Systems Disabled. So if the cannon subsystem is disabled on the FG in question, this condition will trigger. 

![image](https://user-images.githubusercontent.com/43460482/190949824-6230ecb6-d248-458d-8374-4f456e4f1e0e.png)

**Comment by MikeG621** [comment]
Closed via Platform commit [6ac5174](https://github.com/MikeG621/Platform/commit/6ac51747f13445f0bd6e1b76585c5285daa2ea32)
