### ISSUE TITLE
(TIE Fighter) Craft When Variable Type

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#76]
The first four craft when variables are wrong. It should be:

- Captured
- Inspected
- Finished Being Boarded
- Finished Docking

You can also remove the last empty variable in the list.

![image](https://user-images.githubusercontent.com/43460482/190877866-b45192a8-fbcb-48cc-8108-5ce31d48faef.png)
![image](https://user-images.githubusercontent.com/43460482/190878829-9c6a6ff5-ace2-4924-ada5-e99ac6f93e58.png)

**Comment by MikeG621** [comment]
Closed via Platform commit [6ac5174](https://github.com/MikeG621/Platform/commit/6ac51747f13445f0bd6e1b76585c5285daa2ea32)
