### ISSUE TITLE
(TIE Fighter) Status values

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#78]
"No Lasers" should be "No Turrets".

You can also remove values 10 through Invincible, they are not used.

![image](https://user-images.githubusercontent.com/43460482/190879307-356312d1-59e8-4c85-878a-1f3aa33caabc.png)
![image](https://user-images.githubusercontent.com/43460482/190879316-ed2d691f-d03b-4a63-b7db-69df09a0658b.png)
![image](https://user-images.githubusercontent.com/43460482/190879409-7f63a68c-99aa-4934-a0f4-e1719c9119ad.png)

**Comment by MikeG621** [comment]
It's just a simple list, so it's reading/setting the selection position in the drop-down.  If I were to just delete the numbered items, it would set the wrong value and opening a mission with Invincible set would reset to None as it would believe the value isn't supported.  Value 10 is actually used in B11M3MW.

I could redo how it works to trim the list, but the problem there is then I have one drop-down that's handled specially and would have to see how much of a knock-on effect that would have in other parts of the code.

**Comment by bguthrie1** [comment]
I see what you mean. I checked B11M3MW and it seems the planet in the mission uses value 10. There is code that does something with a planet when its status is less than 8. In this case, the developers did not want this code to execute by setting the FG status to 10. But I'm not quite sure what it does. I would allow planets to have their FG status changed. Since we have to work with what we are given with the original missions, perhaps we should keep value 10 in this case.

Is the "Invincible" status used in any mission? Because it doesn't apply invincibility and its not used in the code.

I understand the issue of deleting values would set the wrong value. So if any of the original missions used any of those values, then its ok to keep them. Though if possible trimming the list would be nice.

**Comment by MikeG621** [comment]
I didn't find Invincible actually being used anywhere, that might've been brought over from XvT.

Given that, I think the best course would then be to remove everything after 10, and rename 10 to simply "Unknown"

**Comment by bguthrie1** [comment]
For now, yeah remove everything after 10 and name it unknown. Also I would allow planets to change their FG status. The statuses don't apply to them, but something does happen to them when they are given a FG status less than 8/Shields added.

**Comment by MikeG621** [comment]
The "Status" value for backdrops is what determines which image is used, that's why I have that flipping back and forth in YOGEME.
