### ISSUE TITLE
(TIE Fighter) Order List needs to be fixed

### ISSUE THREAD

**Issue by bguthrie1** [MikeG621/YOGEME#79]
The FG orders up to Board to repair is correct. Everything after that is nullplan/Holding steady and can be removed.

![image](https://user-images.githubusercontent.com/43460482/190935095-c1e67d7a-e58a-41d5-8ba2-a8563f166203.png)

**Comment by MikeG621** [comment]
Go Home 0x23 is used in HI1W.

Does the executable ignore the values about Board to Report, or default to something else?

**Comment by bguthrie1** [comment]
It looks like its used for the player. But players don't use orders. Probably an oversight on the mission editor's part. Does any AI craft use it?

Are you talking about Board to Repair? When you say values, do you mean the variables such as Docking time and number of dockings? If so, then yes the executable does look at those.

**Comment by MikeG621** [comment]
That one case of the player craft is it, I have a scanner and checked every FG of every mission for all three orders, went up past the last SS Disabled by a couple, too.

Yeah, I meant Repair.  I mean if the order is past Board to Repair, is there any action taken or is it ignored entirely as if it was Hold Steady?

**Comment by bguthrie1** [comment]
I will double check when I get home. Whenever you can, please get me the missions of where these extra orders were used.

**Comment by MikeG621** [comment]
[HF1W.zip](https://github.com/MikeG621/YOGEME/files/9630410/HF1W.zip)

**Comment by bguthrie1** [comment]
I've double checked, the game does not look beyond Board to Repair. The zip you posted only has one mission in it and I couldn't find a FG that uses an order beyond Board to Repair.

**Comment by MikeG621** [comment]
[HI1W.zip](https://github.com/MikeG621/YOGEME/files/9635545/HI1W.zip)

Bah, wrong one.  It's the player's FG, Order 1.

**Comment by bguthrie1** [comment]
Yeah I checked that one already. You mentioned other missions where there were FG orders that were going beyond Board to Repair?

**Comment by MikeG621** [comment]
No, I scanned everything and didn't find any others

**Comment by bguthrie1** [comment]
Normally I would just say to remove all the orders after Board to Repair, but it seems YOGEME will throw an exception when loading HI1W if that is done. I'm not sure how to get around that other than listing the orders up to the one the player FG is using in that mission and renaming the unused ones all Hold Steady. 

You could code an exception for that mission though. I'm not fond of that solution though.

**Comment by MikeG621** [comment]
It'll throw due to Out of Bounds, yes.  What I can do though is when reading the file, anything above BtR is ignored and left as Hold Steady, effectively the same thing the EXE is doing.  Then I can remove the extras.  HI1W would technically be modified, as that value would then become zero.

**Comment by bguthrie1** [comment]
Yeah that sounds good. 

By the way I realized in one of my messages above I said "oversight on the mission editor's part" but what I meant was "oversight on the mission creator's part". It is not the first time where I've seen issues like this from the original mission creators where something is off or they used the wrong value and what not. But they didn't bother to fix it in this case since the player doesn't use orders.

**Comment by MikeG621** [comment]
Closed via Platform commit [6ac5174](https://github.com/MikeG621/Platform/commit/6ac51747f13445f0bd6e1b76585c5285daa2ea32)
