### ISSUE TITLE
XWA, Copy selected Team: Idmr.Platform.Xwa.Team+EomMessageIndexer is not marked as Serializable  

### ISSUE THREAD

**Issue by JeremyAnsel** [MikeG621/YOGEME#8]
When copying a team, a `SerializationException` exception is thrown. It says that `Idmr.Platform.Xwa.Team+EomMessageIndexer` is not marked as `Serializable`.

How to reproduce the issue:
- open YOGEME.exe v1.2.5
- select XWA Platform
- select the Teams tab
- click on Copy selected Team

**Comment by MikeG621** [comment]
Fixed for the next upload, also other members of Team were not marked Serializable.
