### ISSUE TITLE
Backdrop window color picker doesnt seem to set color

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#80]
Backdrop window color picker doesn't seem to set color when clicking on specific area of the image.  It does not seem to change the flight group name to match the color

**Comment by MikeG621** [comment]
"specific area": is this common across images, only on
custom/SuperBackdrops, XWA only, etc?  I thought I had fixed that a while
back.

**Comment by ual002** [comment]
I downloaded [v1.13.12] and it wasn't working.  I'm not sure what you were asking me though.  I was just messing with a normal  XWAup install, making a mission from scratch.  Had to scroll to find the backdrop item in the shiplist as I did see any wizard or anthing

**Comment by MikeG621** [comment]
That's right, so I've got it being copied to the clipboard, so you can
paste if you want it added.  Prevents the name being changed by accidental
clicks and not being able to get it back easily.

**Comment by ual002** [comment]
Ill try it

**Comment by MikeG621** [comment]
No, I don't have anything in the program itself, though it's mentioned in
the help file.  Instead of a tooltip, will make it a bit more blatant and
just put another label nearby stating it's on the clipboard.  You're not
the first person to ask about it.
