### ISSUE TITLE
Arrival trigger missing value field

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#82]
The value field presented in Yogme does not appear to be the one that determines region.

![image](https://github.com/MikeG621/YOGEME/assets/7959255/24ce4118-a7c5-4434-80bb-bb29f38d4f0e)

However in allied you can see the value is retained but it isnt the value field that allied thinks specifies the region.

![image](https://github.com/MikeG621/YOGEME/assets/7959255/eb963f2f-5e2c-4360-a2d7-75f5b3067600)

**Comment by MikeG621** [comment]
The drop-down next to Target Type is the correct field, it has the names of the regions listed and will display the correct index.  That extra parameter field is what's used for Regions and Proximity targets, not the normal Variable drop-down.

I could move the fields around, play with enable/disabling them so it's a bit clearer

**Comment by ual002** [comment]
Oh I see what you're saying.  I kind of feel dumb that I missed that.
