### ISSUE TITLE
Wav Manager doesnt support coop mission naming

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#84]
![image](https://github.com/MikeG621/YOGEME/assets/7959255/0eaed0e5-5020-41d2-98ea-74105f6ccc7b)
Using the tour MP hook, missions names beginning in "8" allow up to 8 players if the mission is set up correctly.

**Comment by MikeG621** [comment]
Alright, easy enough to add.  I'll quick turn this, get a release out with
the other pending edit.e ouMessage ID: ***@***.***
com>

>

**Comment by ual002** [comment]
Looks like the popup is updated but something isnt reading the mission name right.
![image](https://github.com/MikeG621/YOGEME/assets/7959255/77aa01c4-5add-4111-8d31-5ff9147dc404)

**Comment by MikeG621** [comment]
Put a letter (non-digit) after the last number, that replicated the stock
naming convention.  The regex it's using is "(1|8)B(\d+)M(\d+)\D\w*".
--

**Comment by ual002** [comment]
Yep that did it.
