### ISSUE TITLE
Backdrop visual list

### ISSUE THREAD

**Issue by ual002** [MikeG621/YOGEME#85]
It appears that no matter what I do to the resdata txt file, the backdrop visual list still shows the same set of backdrops, additionally, adding a backdrop replacer via INI in the hook assignment tool also appears to have no effect on the visual list (but it does affect the dat for actual in game purposes).  Unless I'm missing something, I do think the hook assignment tool, backdrop replacer section is a good way to not only set the dat file for the mission, but hard set the visual catalogue of available backdrops in YOGME rather than relying on resdata text file edits.

**Comment by MikeG621** [comment]
Any custom entries to RESDATA must be at the top, and the original 38 lines
below that.  If the custom entry matches an existing GroupID, then it gets
overridden.  Not something I've looked into, but I would bet that XWA
doesn't load an image if the ID is already occupied, so whatever's first
wins.

For the hook, it's looking for [mission]_Resdata.txt first, then
[mission].ini, and if it's the INI it's looking for the"[Resdata]"
section.  The entries are relative to the base directory, so for example
SuperBackdrops usage has "resdata\planet2.dat".  Then same as just using
RESDATA, it's looking for the DAT's GroupID and replacing it if found.

What does your RESDATA.txt and INI look like?
--

**Comment by ual002** [comment]
Its the TFTC 1.3.3 standard, but I've messed with it since.  Let me see if I can re-upload the mod's file in original state.

All I was saying is that it might be prudent to override YOGME reading any particular dat from the resdata file when a mission ini specifies something else, negating the need to have any particular resdata formatting or order.  All of the TFTC missions include a mission INI and I think all of them specify at lease a different planet.dat.  Its its like pulling teeth getting changes to certain files to stick with all of us doing edits to the mod.  So the backdrop picker could load defaults according to the resdata file, and if is formatted weird, as in the case of TFTC, use the hook assignment tool and overwrite it with an INI, both for the mission in-game and yogme itself

[RESDATA.TXT](https://github.com/MikeG621/YOGEME/files/12292682/RESDATA.TXT)

**Comment by MikeG621** [comment]
It does though.  The INI is loaded last, and YOGEME will override what it
has.
1) Load defaults
2) Override with extra RESDATA lines
3) If the hook is installed, override with INI.

Sounds like it doesn't think you have the hook installed.  If you've got
multiple installs of XWA, make sure that the one you're pointing at (via
Options dialog) has hook_backdrops.dll present in the base directory,
that's what YOGEME is looking for to determine if the backdrop dialog is
launched using the hook or not.
--

**Comment by ual002** [comment]
yeah that dll is present

**Comment by MikeG621** [comment]
I'm going to do a debug build with a couple message boxes to show some
debug info, since I need to see what it's doing on your end.  Should have
that ready tomorrow.
--

**Comment by MikeG621** [comment]
Okay, so this will have two message boxes.  First one is right when you click the backdrops button, lets you know where YOGEME is looking and if it detects the hook.  Second one lists the details of the load.

It's just the EXE renamed so it should run side-by-side in your normal install directory.
[YOGEME-debug.zip](https://github.com/MikeG621/YOGEME/files/12307859/YOGEME-debug.zip)

**Comment by MikeG621** [comment]
Redoing, original attachment didn't work. Zip of the whole debug build.

Okay, so this will have two message boxes. First one is right when you click the backdrops button, lets you know where YOGEME is looking and if it detects the hook. Second one lists the details of the load.
[Debug.zip](https://github.com/MikeG621/YOGEME/files/12307931/Debug.zip)

**Comment by ual002** [comment]
Still appears to load the default images @ 512 x 512 in the editor, but thanks to the mission.ini the larger tftc backdrops are loaded in the mission as before.

 ![image](https://github.com/MikeG621/YOGEME/assets/7959255/51b856d8-9804-490f-bf0e-3f99bfffae4e)
![image](https://github.com/MikeG621/YOGEME/assets/7959255/467d2621-6e5d-42d0-936d-6ed52668166c)
![image](https://github.com/MikeG621/YOGEME/assets/7959255/69c17679-cd3a-4f4c-93e7-a3145bd482cb)

**Comment by MikeG621** [comment]
Well the "default" 512x512 images are really the upsized ones from planet2
that XWAU rolled into the original filenames, since stock images are
256x256 max.  So depending what you're loading (say planet2) then the
images are one and the same.

What's the full contents of the INI?  YOGEME knows the hook exists, but
that says it's not seeing anything in the [Resdata] section, or that the
filename it's looking for doesn't exist.  I think I can see a way for it to
skip through, depending on how the INI's done.
--

**Comment by ual002** [comment]
INI was just what the wizard was adding. 

;8B84M9B.ini

[Resdata]
Resdata\PlanetTFTC.dat

This is stuff in the Combat folder though, not the mission folder.

**Comment by MikeG621** [comment]
Well that's the problem then, it's looking for the INI in the \Missions
directory.  I can make the change so it follows whichever directory it's
sitting in.  The BackdropDialog handles it a little differently since it
normally has no need to know what the mission is.

YOGEME wasn't designed with \COMBAT in mind, as hardly anyone ever messed
with those due to the difficulties with co-op prior to the existence of the
hooks.  Similar to the WAV issue, you're likely the first person in the 15
years since I started it to make a serious effort with multiplayer, so
you're likely to keep running into little things like this.
--
