### ISSUE TITLE
(XWA) missing Arrival/Departure & Goals Triggers

### ISSUE THREAD

**Issue by Blazingfirestorm** [MikeG621/YOGEME#89]
so if the first condition is counted as 0
the 58 trigger is NOT be identified
the 55 trigger is All Disabled
the 51 trigger is All Seized
the 38 trigger is (Always Failed)
the 39 trigger is inspect/pickup for team

**Comment by MikeG621** [comment]
39, does that also require the Team number be referenced in the Parameter?  Is it based on inspection, or pick up?
51, All captured?  I'd like the verbiage be consistent.

**Comment by Blazingfirestorm** [comment]
All captured that works

as for 39 the only time I've seen it used in XWA is B1M5 as a global prevent condition  100% of Scavengers must unknown and and I look at XVT and the position of the conditions matches up

**Comment by MikeG621** [comment]
That helps, I've got notes in my XvT format spec about how 39 works

**Comment by Blazingfirestorm** [comment]
I assume it works the same

**Comment by MikeG621** [comment]
Listing fixed in [Platform v5.8.1](https://github.com/MikeG621/Platform/releases/tag/v5.8.1), need to check for special handling before this'll be closed.
