### ISSUE TITLE
Briefing event limit error

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#92]
I was making a briefing and adding move commands. The move command made the event list go over the hard limit for the allow number of them. It gave me an error but still allowed me to save. It then would not let me reopen the briefing window to delete the offending events and as I had saved it, there was no way back. I had to open in ALLiED to be able to open the briefing and delete the events tab to clear the error.

**Comment by MikeG621** [comment]
Do you still have a copy of the broken mission that you can attach?
--
