### ISSUE TITLE
(XWA) mission map issue

### ISSUE THREAD

**Issue by Blazingfirestorm** [MikeG621/YOGEME#93]
if a hyper buoy has the role of HYP from any region the FG that uses it isn't position on it but in game they do exit in the right place 
![image](https://github.com/MikeG621/YOGEME/assets/147922498/dac09b89-a1d3-44e6-a919-543d69ca8da3)

in allied they are positions right 
![image](https://github.com/MikeG621/YOGEME/assets/147922498/4b89f4bb-fd22-4269-a987-58a407ab009e)

**Comment by MikeG621** [comment]
Yeah, I haven't rolled that in yet, need to hack that into all of the buoy
checks.

**Comment by Blazingfirestorm** [comment]
cool
