### ISSUE TITLE
(XWA) unable to disable waypoint 1 on Hyper orders

### ISSUE THREAD

**Issue by Blazingfirestorm** [MikeG621/YOGEME#94]
in the vanilla game many orders with hyper orders have the waypoints disable due to the craft just flying to the hyper point but with yogeme the first waypoint in turn on without the ability to turn it off so now the craft is flying toward 0,0,0 before hypering out

**Comment by MikeG621** [comment]
So this is just for the jump *to* hyperspace?  Because the last WP on the
hyper order is used to determine the offsets at the exit side, so if none
of them are enabled how XWA handles the exit in that case will need to be
determined.

**Comment by Blazingfirestorm** [comment]
yes this issue was for the hyper to region #  order specifically in B1M2 FG FRS Andrasta second order in region #2 were he starts

**Comment by Blazingfirestorm** [comment]
nice stealth fix

**Comment by MikeG621** [comment]
?  I didn't do anything to address this one yet.  Are you saying the issue
is no longer there?Message ID: ***@***.***
com>

>

**Comment by Blazingfirestorm** [comment]
well now if you have 0 0 0 and unselect it stays unselected

**Comment by Blazingfirestorm** [comment]
ok it's still an issue then

**Comment by MikeG621** [comment]
It's happening with all craft, type doesn't matter.  It gets enabled when the map is opened and seems to be limited to the hyper order when WP2 is also disabled.  If WP2 is checked, it's not checking WP1.
Trying to track it down, I know it's related to the calculation of the hyper points, just need to find the reference that's not doing what I want.
