### ISSUE TITLE
XWAU not detected

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#95]
I have multiple installations of XWA. One that is "vanilla" 2.02 XWA, one that is TFTC, and one that is XWAU 6.0. YOGEME knows which version I am editing in for the wire frames in the map screen and craft list. But does not let me add super backdrops or use the hook editor, or show the XWAU/TFTC backdrops in the selection window either.

I think this is because I have the "main" (registry location) folder as the vanilla XWA, but for other reasons, I want the registry location to stay vanilla. 

Is it possible to make it a selection tick to say whether you want to add super backdrops or hook editor rather than it being a registry check?

**Comment by MikeG621** [comment]
Within the settings you can change which directory YOGEME is pointing to
for the installation it references for SBD, hooks, etc.Message ID:
***@***.***>

>

**Comment by JaggedFellIII** [comment]
I will check that out thanks

**Comment by JaggedFellIII** [comment]
That worked
