### ISSUE TITLE
Craft count

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#96]
Is it possible to not have asteroids and other objects count in the craft count? Also, is it possible to add FG counters and object counters?

**Comment by MikeG621** [comment]
For me to remove counting them in YOGEME I would need confirmation that the game doesn't count them, which I don't believe is the case.

There's already a FG counter on the Craft tab, "Flight Group #X of X"

**Comment by JaggedFellIII** [comment]
See this post from the XWAU forum

https://www.xwaupgrade.com/phpBB3008/viewtopic.php?p=175228#p175228

**Comment by MikeG621** [comment]
Okay, so the thread has that asteroids/objects do count towards the FG
limit, but not the craft limit due to the separate object table.  That'll
take a bit of doing, since preferably it'd scan the FG stats from the
executable to determine which category it belongs to.

**Comment by MikeG621** [comment]
For the CraftLimit, are you just talking about the Verify utility when you save?

**Comment by JaggedFellIII** [comment]
I believe so.

**Comment by MikeG621** [comment]
Closing, moving the external portion to [MissionVerify](https://github.com/MikeG621/MissionVerify/issues/4)
