### ISSUE TITLE
Listing Global Unit and Global Group memebers

### ISSUE THREAD

**Issue by LPhoenix21** [MikeG621/YOGEME#97]
Would it be possible to create a small tool or something to be able to list the currently used Global Units and Global Groups to know which Flight Groups are their members?

Could be a useful tool during mission development

**Comment by MikeG621** [comment]
The Global Groups and Global Units are already in the FlightGroup list, so
they're all visible at once.  Are you asking for a separate window?

**Comment by LPhoenix21** [comment]
Yes it's there, but with a lot of Flight Groups in a mission, you can't see all the Flight Groups at the same time and it makes hard to spot the info

Yeah, probably a separate window would work
