### ISSUE TITLE
Backdrops fail to load

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#98]
With the update to XWAU 6.0/TFTC 1.3.4 YOGEME won't pull up the backdrop viewer/browser. If you know the backdrop number and shadow you can still enter that information into the backdrop dialog but you cannot open the preview window. It just says

Cannot open resource file: \Resdata\planet.dat
Check your platform installation path

I reinstalled and checked at each point and YOGEME had no problems with TFTC 1.3 and 1.3.3 but once updated to 1.3.4 it won't work anymore.

**Comment by MikeG621** [comment]
Working on updating my XWA install to see what's wrong

**Comment by MikeG621** [comment]
So, the root of the problem is with the new DATs created for XWAU 6.  They added a new compression format that I'll need to work in before that'll work again.

**Comment by JaggedFellIII** [comment]
Ok, thanks for the update.

**Comment by MikeG621** [comment]
Okay, add the latest [Dat](https://github.com/MikeG621/ImageFormat-Dat/releases/download/v2.5/DatWithBcnDlls.zip) library to YOGEME's bin directory and that should take care of it.

**Comment by JaggedFellIII** [comment]
How do you do that?

**Comment by MikeG621** [comment]
Unzip that file I linked to into the \bin\ folder wherever you installed
YOGEME.

**Comment by JaggedFellIII** [comment]
That worked, thanks
