### ISSUE TITLE
False Arrival Errors

### ISSUE THREAD

**Issue by JaggedFellIII** [MikeG621/YOGEME#99]
It seems that if you change the radio selection button between the two arrival trigger blocks from "and" to "or" it will give an arrival condition error message on saving, even if there are no errors

**Comment by MikeG621** [comment]
I'm going to need a full list of how the blocks are defined, that's not enough to go on.

**Comment by JaggedFellIII** [comment]
So you know how on the arrival tab for a FG there are two conditions that
you can set with an and/or selection to the right and then an another two
conditions that you can set with an and/or selection on the right and
between the two sets of conditions? In my testing/experience if the and/or
between the two sets is made a "or" it gives an error warning when saving

**Comment by MikeG621** [comment]
Again, I need all 4 triggers.  I can't look for a problem if you don't tell me exactly what you're doing.  Flipping that value by itself doesn't tell me anything.

**Comment by JaggedFellIII** [comment]
It seems to happen irregardless of the conditions. I am using mostly
message #X has been shown or message #you has been shown or message #z has
been shown. But is also happens if instead it is a certain flight group has
arrived or been destroyed as one or more of the triggers. The commonality
seems to me to be that and/or selection.

And I have tested function in game and the FG arrives without issue

**Comment by MikeG621** [comment]
So the [Verfiy](https://github.com/MikeG621/MissionVerify) tool was supposed to be looking at the Departure And/Or, not 1/2 And/Or 3/4.  So that's why it wasn't making sense.
Re-posted 1.15.5 with the new Verify tool.

**Comment by JaggedFellIII** [comment]
Ok, thanks.
